const autocannon = require('autocannon');
const fs = require('fs');
const path = require('path');

const targetUrl = process.env.TARGET_URL || 'http://localhost:3000';
const connections = parseInt(process.env.CONNECTIONS || '50', 10);
const duration = parseInt(process.env.DURATION || '10', 10);

console.log('======================================================');
console.log('            GL BAJAJ T&P PORTAL LOAD TEST             ');
console.log('======================================================');
console.log(`Target URL:  ${targetUrl}`);
console.log(`Connections: ${connections}`);
console.log(`Duration:    ${duration} seconds`);
console.log('======================================================\n');

async function benchmark(routePath, title) {
  console.log(`[+] Starting test for ${title} (${routePath})...`);
  try {
    const result = await autocannon({
      url: `${targetUrl}${routePath}`,
      connections,
      duration,
      pipelining: 1,
      headers: {
        'user-agent': 'Autocannon Load Tester',
        'x-request-id': 'load-test-' + Date.now(),
      }
    });

    console.log(`[✓] Completed test for ${title}.`);
    console.log(`    Req/Sec (Avg): ${result.requests.average}`);
    console.log(`    Latency (Mean): ${result.latency.mean} ms`);
    console.log(`    Latency (p99):  ${result.latency.p99} ms`);
    console.log(`    Errors/Timeouts: ${result.errors + result.timeouts}\n`);

    return result;
  } catch (err) {
    console.error(`[✗] Failed to benchmark ${title}:`, err);
    return null;
  }
}

function formatResultMarkdown(title, path, result) {
  if (!result) {
    return `### ${title} (${path})\n\n**Failed to complete benchmark.**\n`;
  }
  return `### ${title} (${path})

| Metric | Value |
| :--- | :--- |
| **Average Requests/sec** | ${result.requests.average} |
| **Total Requests** | ${result.requests.total} |
| **Average Latency** | ${result.latency.average} ms |
| **Mean Latency** | ${result.latency.mean} ms |
| **p50 Latency (Median)** | ${result.latency.p50} ms |
| **p90 Latency** | ${result.latency.p90} ms |
| **p99 Latency** | ${result.latency.p99} ms |
| **Max Latency** | ${result.latency.max} ms |
| **Throughput** | ${(result.throughput.average / 1024 / 1024).toFixed(2)} MB/sec |
| **Total Bytes Received** | ${(result.throughput.total / 1024 / 1024).toFixed(2)} MB |
| **Total Errors** | ${result.errors} |
| **Total Timeouts** | ${result.timeouts} |
| **Status Codes** | 2xx: ${result['2xx']}, 3xx: ${result['3xx']}, 4xx: ${result['4xx']}, 5xx: ${result['5xx']} |
`;
}

async function main() {
  const landingResult = await benchmark('/', 'Landing Page');
  const csrfResult = await benchmark('/api/auth/csrf', 'CSRF Endpoint');

  const reportContent = `# Load Test Report

**Date**: ${new Date().toLocaleString()}
**Target URL**: ${targetUrl}
**Configuration**:
- Concurrent Connections: ${connections}
- Duration: ${duration} seconds

${formatResultMarkdown('Landing Page', '/', landingResult)}

${formatResultMarkdown('CSRF Endpoint', '/api/auth/csrf', csrfResult)}

---
*Generated by Autocannon Load Testing Suite.*
`;

  const reportPath = path.join(__dirname, 'report.md');
  fs.writeFileSync(reportPath, reportContent);
  console.log(`[✓] Load test complete. Report saved to: ${reportPath}`);
}

main();
